### ISSUE TITLE
Add support for path, emoji, and hash tokens in `interpolateName`

### ISSUE THREAD

**Issue by vseventer** [erikdesjardins/spawn-loader#14]
Right now, `spawn-loader` does not support the `path`, `emoji`, and `hash` tokens from [`loaderUtils.interpolateName`](https://github.com/webpack/loader-utils#interpolatename). I know `path` is supported with a separate query param, but especially `hash` is not, which is an issue, as the generated filename will have these tokens evaluated.

For example:
```js
const url = require('spawn-loader?name=[name].[hash:6].js');
// url = "chunk-name.[hash:6].js" (unevaluated token)
// generated file by spawn-loader = "chunk-name.abcdef.js" (evaluated token)
```

I have created something that works for me [here](https://github.com/vseventer/spawn-loader/commit/da17055517e4083e38661e3f017f3dabca1e5033), but I don't know enough of the Webpack compiler internals to come up with a better solution. For what it is worth, `entry-loader` does support this properly. Ideas / suggestions?

**Comment by erikdesjardins** [comment]
Yeah, hash is a glaring omission. Your quick and dirty solution is pretty much the best I can come up with too.

It's nontrivial to support `[emoji]`. since it seems only loaderUtils supports it and not Webpack itself (at least in Webpack 3.3), so I don't want to unless someone really wants it.

AFAICT `[path]` doesn't make sense unless this loader has a `context` option to pass through to loaderUtils; I don't see anything that the loader receives that would make sense to use (`this.context` makes it always an empty string). I could add an option if you need it.
